controller_list:
  - name: fake_head_controller
    joints:
      - spine_0
      - spine_1
      - spine_2
      - neck_0
      - neck_1
      - neck_2
  - name: fake_right_arm_controller
    joints:
      - right_shoulder_0
      - right_shoulder_1
      - right_shoulder_2
      - right_elbow_0
      - right_elbow_1
      - right_wrist_0
      - right_wrist_1
  - name: fake_left_arm_controller
    joints:
      - left_shoulder_0
      - left_shoulder_1
      - left_shoulder_2
      - left_elbow_0
      - left_elbow_1
      - left_wrist_0
      - left_wrist_1
  - name: fake_right_leg_controller
    joints:
      - right_hip_0
      - right_hip_1
      - right_hip_2
      - right_knee
      - right_ankle_0
      - right_ankle_1
  - name: fake_left_leg_controller
    joints:
      - left_hip_0
      - left_hip_1
      - left_hip_2
      - left_knee
      - left_ankle_0
      - left_ankle_1