- /kinect_frame
- /optitrack/human/base
- /optitrack/human/head
- /optitrack/human/spine
- /optitrack/human/right_elbow
- /optitrack/human/left_elbow
- /optitrack/human/right_hand
- /optitrack/human/left_hand
- /shapeo