<?xml version="1.0"?>
<robot xmlns:xacro="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface" name="human_model" >
       
<xacro:include filename="props_global.urdf.xacro" />
 
<xacro:macro name="human_body">
	  <link name="base">
      <visual>
        <origin xyz="0 0 ${-hip_offset_height/2}" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${hip_offset_width+thigh_radius}" length="${-hip_offset_height}" />
        </geometry>
      </visual>
    </link>

    <link name="spine_0">
      <visual>
        <origin xyz="0 0 ${spine_down_length/2}" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${spine_down_radius}" length="${spine_down_length}" />
        </geometry>
      </visual>
    </link>

    <link name="spine_1"/>
    <link name="spine_2"/>

    <link name="spine">
      <visual>
        <origin xyz="0 0 ${spine_up_length/2}" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${spine_up_radius}" length="${spine_up_length}" />
        </geometry>
      </visual>
    </link>

    <link name="shoulder_center">
      <visual>
        <origin xyz="0 0 ${torso_length/2}" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${torso_radius}" length="${torso_length}" />
        </geometry>
      </visual>
    </link>

    <link name="neck_0"/>
    <link name="neck_1"/>
    
    <link name="neck">
      <visual>
        <origin xyz="0 0 ${neck_length/2}" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${neck_radius}" length="${neck_length}" />
        </geometry>
      </visual>
    </link>

    <link name="head">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
	        <sphere radius="${head_radius}" />
        </geometry>
      </visual>
    </link>

    <joint name="hip" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <parent link="base" />
      <child link="spine_0" />
    </joint>

    <!-- SPINE : spherical -->
    <joint name="spine_0" type="revolute">
      <origin xyz="0 0 ${spine_down_length}" rpy="0 0 0" />
      <axis xyz="1 0 0" />
      <parent link="spine_0" />
      <child link="spine_1" />
      <limit lower="${-PI_DIV_2}" upper="${PI_DIV_2}" effort="${max_effort}" velocity="${max_velocity}" />
    </joint>

    <joint name="spine_1" type="revolute">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <axis xyz="0 1 0" />
      <parent link="spine_1" />
      <child link="spine_2" />
      <limit lower="${-PI_DIV_2}" upper="${PI_DIV_2}" effort="${max_effort}" velocity="${max_velocity}" />
    </joint>
    
    <joint name="spine_2" type="revolute">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <axis xyz="0 0 1" />
      <parent link="spine_2" />
      <child link="spine" />
      <limit lower="${-PI_DIV_2}" upper="${PI_DIV_2}" effort="${max_effort}" velocity="${max_velocity}" />
    </joint>

    <joint name="shoulder_center" type="fixed">
      <origin xyz="0 0 ${spine_up_length}" rpy="0 0 0" />
      <parent link="spine" />
      <child link="shoulder_center" />
    </joint>

    <!-- NECK : spherical -->
        <joint name="neck_0" type="revolute">
          <origin xyz="0 0 ${torso_length}" rpy="0 0 0" />
          <axis xyz="1 0 0" />
          <parent link="shoulder_center" />
          <child link="neck_0" />
          <limit lower="${-PI_DIV_2}" upper="${PI_DIV_2}" effort="${max_effort}" velocity="${max_velocity}"  />
        </joint>

        <joint name="neck_1" type="revolute">
          <origin xyz="0 0 0" rpy="0 0 0" />
          <axis xyz="0 1 0" />
          <parent link="neck_0" />
          <child link="neck_1" />
          <limit lower="${-PI_DIV_2}" upper="${PI_DIV_2}" effort="${max_effort}" velocity="${max_velocity}"  />
        </joint>

        <joint name="neck_2" type="revolute">
          <origin xyz="0 0 0" rpy="0 0 0" />
          <axis xyz="0 0 1" />
          <parent link="neck_1" />
          <child link="neck" />
          <limit lower="${-PI_DIV_2}" upper="${PI_DIV_2}" effort="${max_effort}" velocity="${max_velocity}" />
        </joint>
    <!-- END NECK -->

    <joint name="head" type="fixed">
      <origin xyz="0 0 ${neck_length}" rpy="0 0 0" />
      <parent link="neck" />
      <child link="head" />
    </joint>

</xacro:macro>

</robot>
